### ISSUE TITLE
AttributeError: 'Proj' object has no attribute 'is_latlong'

### ISSUE THREAD

**Issue by chrimerss** [mdbartos/pysheds#101]
This problem occurs when calling grid.cell_slopes().
I think Proj>2.2.0 has removed attribute is_latlong.

**Comment by KMarkert** [comment]
I was having the same problem. You are correct in that it is a pyproj version issue. You can solve this by explicitly installing a pyproj version before 2.2 (2.1 works just fine).

**Comment by mdbartos** [comment]
Thanks for your patience. @KMarkert is correct. I will take a look at patching this when I get some time next week. (Also, feel free to submit pull requests if you find that anything is broken).

**Comment by mdbartos** [comment]
Greetings. This has been resolved in PR #108 (allows for versions of pyproj both > or < 2.2). Let me know if you encounter any more problems.

**Comment by LorenzoBottaccioli** [comment]
@mdbartos still have the issue in version 2.5 and 3.0.1

ciao

**Comment by mdbartos** [comment]
Greetings. The offending code was removed in v0.3. I'd recommend upgrading.
